baseurl = "/"
languageCode = "en-GB"
title = "Random R stuff"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-129716792-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Asper the config (does not have Asian language)
hasCJKLanguage = false

[params]
    author = "Konrad Zdeb"
    description = "Personal blog on R, business intelligence, data science and statistics"
    Subtitle = "Fun with R and other languages"
    twitter = "konradzdeb"

    # Provide summary
    enableSummary = true

    # Show twitter
    enableTwitterCard = true

    # show latest posts in single page
	showLatestPosts = true

    # Show nice icons
    iconFont = "font-awesome"

    enableRSS = true
	enableToc = true

# Add additional social link entries underneath
[social]
	twitter = "https://www.twitter.com/konradzdeb"
	github = "https://www.github.com/konradedgar"
	linkedin = "https://uk.linkedin.com/in/konradz"
	stack-overflow = "https://stackoverflow.com/users/1655567/konrad"
