baseurl = "/"
languageCode = "en-GB"
title = "Random R stuff"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-129716792-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Asper the config (does not have Asian language)
hasCJKLanguage = false


[permalinks]
post = "/:year/:month/:day/:slug/"

[params]
    author = "Konrad Zdeb"
    description = "Personal blog on R, business intelligence, data science and statistics"
    twitter = "konradzdeb"
    # Provide summary
    enableSummary = true
    # Show twitter
    enableTwitterCard = true

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "Tomorrow"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    Subtitle = "Fun with R and other languages"
    Content = false  # takes true or false
    # if both are set to true, summary is shown.
    # FooterMsg = "Copyright Me 2016. Powered by Hugo."
